### ISSUE TITLE
Automatisk oversettelse av nettsiden?

### ISSUE THREAD

**Issue by kfalvestad** [echo-webkom/echo-web-mono#1841]

**Comment by omfj** [comment]
Usikker på om det er noe ordentlig god måte å gjøre det på. Koden blir rar, og muligens må vi gjøre masse api spørringer.

**Comment by Herwal** [comment]
mulig start? https://medium.com/flycode/step-by-step-how-to-internationalize-your-nextjs-app-with-next-translate-3c8b13b87fc4

**Comment by omfj** [comment]
Krever vel at vi oversetter ting manuelt. Vi hadde det sånn før, men det endte opp med at ingen orket å fikse det etter hvert.

Jeg mener jo at vi bare kan få folk til å bruke translate-funksjonen som er innebygd i de fleste nettlesere.

**Comment by Herwal** [comment]
Hehe ja dette var mest på gøy, ble ganske dårlig og 🤣
